### ISSUE TITLE
Connection not made to server from mobile chrome browser 59.0.3071.125

### ISSUE THREAD

**Issue by FreddieOD** [wburgers/websocket-component#5]
Hello and thank you for this component. A websocket handshake is successful when initiated from my desktop browser chrome 57.0.2987.110 (64-bit). On my mobile browser chrome 59.0.3071.125 Android 4.3.0 no such handshake message is made to my server. Could be a chrome version or mobile browser issue? I doubt it has to do with my old Android version.

**Comment by wburgers** [comment]
Hey Freddie,

Are you trying to set up a secure connection?
If so I would recommend checking [here](https://www.ssllabs.com/ssltest/) to see if the handshake is rejected on some platforms.
This could be due to supported cipher suites or other SSL settings.
Those settings in Android depend mostly on the operating system and its version.
Android 4.3.0 depends upon TLS 1.0 according to ssllabs.
Perhaps that is blocked by the server?

If you are not trying on a secure connection. I can dig some more, but this is probably between de browser and the server and not so much inside my webcomponent I think.
The webcomponent just wraps the native javascript calls in an html element...

**Comment by FreddieOD** [comment]
Hello there!

Thanks for getting back to me. No it is not an ssl connection. Interestingly no connection is even attempted.  I will investigate further tonight. I have tested across browsers on desktop and all works fine. I will post my updates (might just very well be my own issue with server configuration?).

**Comment by wburgers** [comment]
Hey,

Yeah, I am sorry it took a while.

In that case I am very interested in what the debug tools in chrome might be able to tell you.
Can you connect your phone to chrome on the desktop and try remote debugging?
Under the Network tab, you should be able to see the UPGRADE request being made to open the socket.
Furthermore the console might be interesting.

Hope to be of any help!

**Comment by wburgers** [comment]
@FreddieOD Can this issue be closed?

**Comment by FreddieOD** [comment]
Hey
Yes it can. I will do so now.
